# Generated by Django 3.0.5 on 2020-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=120)),
                ('notice_description', models.TextField()),
                ('notice_image', models.ImageField(null=True, upload_to='')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='indeximage',
            name='index_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
