# Generated by Django 3.0.5 on 2020-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardofDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=120, null=True)),
                ('director_designation', models.CharField(max_length=120, null=True)),
                ('director_image', models.ImageField(null=True, upload_to='')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
