# Generated by Django 3.0.5 on 2020-04-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_gallerimage_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GallerImage',
            new_name='GalleryImage',
        ),
    ]
