# Generated by Django 3.0.5 on 2020-04-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20200428_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Staff',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_designation',
            new_name='staff_designation',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_image',
            new_name='staff_image',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_name',
            new_name='staff_name',
        ),
    ]
