# Generated by Django 3.0.5 on 2020-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20200428_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
