# Generated by Django 3.0.5 on 2020-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_staff_staff_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_telephone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
