# Generated by Django 3.0.5 on 2020-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20200428_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardofdirector',
            name='director_telephone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
