# Generated by Django 3.0.5 on 2020-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_boardofdirector_director_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff')], default='teaching', max_length=120, null=True),
        ),
    ]
